include::header.adoc[]

:title: Assignment 1: Learn to C!
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1

= {title}

**Due Thursday, September 15, before midnight**

The goals for this assignment are:

* Work with printf and scanf
* Practice C syntax: variables, functions, loops, structs, arrays, strings

:sectnums:

= Shift Cypher

Write a program, `cypher.c`, that asks the user for a word and then encodes it using a shift cypher. A shift cypher replaces each letter with a letter that is X positions from it in the alphabet. For example, is the letter is 'a' and the shift is 2, we replace 'a' with a 'c'. You can assume that all inputs are lowercase and do not contain special characters.  

[source,subs="quotes"]
----
$ **make cypher**
gcc cypher.c -o cypher
$ **./cypher**
Enter a word: **elephant**
Enter a shift: **2**
Your cypher is gngrjcpv
$ **./cypher **
Enter a word: **gngrjcpv**
Enter a shift: **-2**
Your cypher is **elephant
$ **./cypher **
Enter a word: **hello**
Enter a shift: **7**
Your cypher is olssv
$ **./cypher **
Enter a word: **a**
Enter a shift: **-2**
Your cypher is y
$ **./cypher **
Enter a word: **z**
Enter a shift: **2**
Your cypher is b
----

= Restaurants

Write a program, `restaurants.c`, that maintains a list of restaurants. 

[source,subs="quotes"]
----
$ **make restaurants**
gcc restaurants.c -o restaurants

$ **./restaurants**
Welcome to Steven Struct's Restarant List.

What hour is it (24 hr clock)? **10**

0) Sushi Atsumi         open: 11:00     close: 23:00    stars: 3.5
1) The Thirsty Horse    open: 17:00     close: 02:00    stars: 4.5
2) Magic Bean Coffee    open: 06:00     close: 15:00    stars: 4.1

What restaurant do you want to visit? [0,1,2] 2
Excellent choice. Magic Bean Coffee will be open for 5 more hours

$ **./restaurants**
Welcome to Steven Struct's Restarant List.

What hour is it (24 hr clock)? **10**

0) Sushi Atsumi         open: 11:00     close: 23:00    stars: 3.5
1) The Thirsty Horse    open: 17:00     close: 02:00    stars: 4.5
2) Magic Bean Coffee    open: 06:00     close: 15:00    stars: 4.1

What restaurant do you want to visit? [0,1,2] 0
Sushi Atsumi isn't open until 11 o'clock!!

$ **./restaurants**
Welcome to Steven Struct's Restarant List.

What hour is it (24 hr clock)? **3**

0) Sushi Atsumi         open: 11:00     close: 23:00    stars: 3.5
1) The Thirsty Horse    open: 17:00     close: 02:00    stars: 4.5
2) Magic Bean Coffee    open: 06:00     close: 15:00    stars: 4.1

What restaurant do you want to visit? [0,1,2] 1
The Thirsty Horse closed at 2 o'clock!!
----

Requirements:

* Your program should define a `struct restaurant` that stores a name, opening hour (int), closing hour (int) and stars rating (float or double) 
* Your program should define at least three snacks and store them in an array
* Your program should be similar to the given output but feel free to customize it!
* Your program should handle establishments that are open over midnight, like The Thirsty Horse.

= Wordle

Write a program, `wordle.c`, that implements the game 
link:https://wordlewebsite.com[Wordle]. Your program should choose a 
random 5-letter word from a list and then give the user 6 tries to 
guess the word. Each guess, your program should tell the user what letters 
are 

* In the correct place
* In the word, but in the wrong place
* Not in the word

[source,subs="quotes"]
----
$ **make wordle**
gcc wordle.c -o wordle
$ **./wordle**
Welcome to Wordle!

You guessed it!
----

Requirements and hints:

* Your program should implement at least one function. Try to keep your program DRY (e.g. Don't Repeat Yourself!)
* Use the `rand()` function (defined in `stdlib.h`) to choose a random word from the pre-defined variable words.
* Your output should be similar to the sample output, although you can customize it!
* Your program should print out whether the user guessed the word correctly or not. If the user doesn't guess the word, you should tell the user the word. 

NOTE: The code `srand(time(0));` sets up the `rand()` function to produce different random numbers every time you run the program. 
Comment this line out, to run with the same random numbers. This can be useful for testing.

= Submit your Work

Push you work to github to submit your work.

[source]
----
$ cd A01
$ git status
$ git add *.c 
$ git status
$ git commit -m "assignment 1 complete"
$ git status
$ git push
$ git status
----

